version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
  spring-milestones:
    type: maven-repository
    url: https://repo.spring.io/milestone
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-central
      - spring-milestones
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    open-pull-requests-limit: 10
    labels: ["type: dependency-upgrade"]
    groups:
       development-dependencies:
         update-types: ["patch"]
         patterns: 
         - "com.gradle.enterprise"
         - "io.spring.*"
         - "org.ajoberstar.grgit"
         - "org.antora"
         - "io.micrometer:micrometer-docs-generator"
         - "com.willowtreeapps.assertk:assertk-jvm"
         - "org.hibernate.validator:hibernate-validator"
         - "org.apache.httpcomponents.client5:httpclient5"
         - "org.awaitility:awaitility"
         - "com.google.code.findbugs:jsr305"
         - "org.xerial.snappy:snappy-java"
         - "org.lz4:lz4-java"
         - "com.github.luben:zstd-jni"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels: ["type: task"]
    groups:
      development-dependencies:
        patterns:
          - "*"
