on:
  workflow_dispatch:
    inputs:
      milestone:
        description: 'Release version like 5.0.0-M1, 5.1.0-RC1, 5.2.0 etc.'
        required: true

jobs:
  finalize:
    uses: spring-io/spring-github-workflows/.github/workflows/spring-finalize-release.yml@main
    with:
      milestone: ${{ inputs.milestone }}
    secrets:
      GH_ACTIONS_REPO_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      SPRING_RELEASE_CHAT_WEBHOOK_URL: ${{ secrets.SPRING_RELEASE_GCHAT_WEBHOOK_URL }}
